name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

permissions:
  contents: read
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Simulate failure for testing
        run: exit 1

      - name: Create issue if failure or cancellation
        if: failure() || cancelled()
        uses: JasonEtco/create-an-issue@v2
        with:
          update_existing: false
          title: "Build {{ github.workflow }} run #{{ github.run_id }}: {{ job.status }}"
          body: |
            ⚠️ Job ended with status **{{ job.status }}**.
            Repository: {{ github.repository }}
            Logs: {{ github.server_url }}/{{ github.repository }}/actions/runs/{{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
