name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  code-quality:
    name: Code quality
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run linting
        run: bash run_linting.sh

  tests:
    name: Tests - ${{ matrix.os }}
    needs:
      - code-quality
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-13
          - windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: bash run_tests.sh

  notify:
    name: Notify failed build
    needs:
      - code-quality
      - tests
    if: failure() && github.event.pull_request == null
    runs-on: ubuntu-latest
    steps:
      - uses: jayqi/failed-build-issue-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
