name: CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: read
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 🚨 Uncomment this block to test a failure
      # - name: Simulate failure
      #   run: exit 1

      - name: Create GitHub issue on failure or cancellation
        if: failure() || cancelled()
        uses: bryannice/gitactions-git-issue-creation@2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_COMMIT_SHA: ${{ github.sha }}
          GITHUB_REPO_OWNER: ${{ github.repository_owner }}
          GITHUB_REPO_NAME: ${{ github.repository }}
          GITHUB_ISSUE_TITLE: "Workflow: ${{ github.workflow }} #${{ github.run_number }} — ${{ job.status }}"
          GITHUB_ISSUE_BODY: |
            ⚠️ The build job in workflow **${{ github.workflow }}** (run #${{ github.run_number }}) ended with **${{ job.status }}**.
            Logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
