name: CI
 
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
 
jobs:
 
  build:
    runs-on: [ubuntu-24.04-s390x, ubuntu-24.04-ppc64le]
    strategy:
      matrix:
        arch: [s390x, ppc64le]
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "Hello, world! GitHub app is running successfully."
 
        
  code-quality:
    name: Code quality
    runs-on: [ubuntu-24.04-s390x, ubuntu-24.04-ppc64le]
    steps:
      - uses: actions/checkout@v4
      - name: Run linting
        run: bash run_linting.sh
 
  tests:
    name: Tests
    needs:
      - code-quality
    runs-on: [ubuntu-24.04-s390x, ubuntu-24.04-ppc64le]
   
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: bash run_tests.sh
 
  notify:
    name: Notify failed build
    needs:
      - code-quality
      - tests
    if: failure() && github.event.pull_request == null
    runs-on: [ubuntu-24.04-s390x, ubuntu-24.04-ppc64le]
    steps:
      - uses: jayqi/failed-build-issue-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
